import { Router } from 'express';
import authRoutes from './auth';
import deviceRoutes from './devices';
import commandRoutes from './commands';
import userRoutes from './users';
import roleRoutes from './roles';
import alertRoutes from './alerts';
import securityRoutes from './security';
import auditRoutes from './audit';
import dashboardRoutes from './dashboard';
import settingsRoutes from './settings';
import networkRoutes from './network';
import groupsRoutes from './groups';
import policiesRoutes from './policies';
import softwareRoutes from './software';
import notificationsRoutes from './notifications';
import mfaRoutes from './mfa';
import reportsRoutes from './reports';
import ssoRoutes from './sso';

const router = Router();

router.use('/auth', authRoutes);
router.use('/devices', deviceRoutes);
router.use('/commands', commandRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/alerts', alertRoutes);
router.use('/security', securityRoutes);
router.use('/audit', auditRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/settings', settingsRoutes);
router.use('/network', networkRoutes);
router.use('/groups', groupsRoutes);
router.use('/policies', policiesRoutes);
router.use('/software', softwareRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/mfa', mfaRoutes);
router.use('/reports', reportsRoutes);
router.use('/sso', ssoRoutes);

export default router;
